functional:
- Пользователь должен иметь возможность зарегистрироваться 
- Пользователь должен иметь возможность авторизоваться
- Пользователь должен иметь возможность создать игру с ботом
- Пользователь должен иметь возможность создать игру с любым пользователем
- Пользователь должен иметь возможность создать турнир
- Созданная игра пользователем должны быть доступна по ссылке
- Пользователь должен иметь возможность менять язык программирования во время игры
- Пользователь должен иметь возможность выбрать уровень сложности в игре
- Пользователь должен иметь возможность выбрать язык в игре (Русский, English)
- Другие пользователи должны иметь возможность следить за ходом игры
- Зарегистрированные пользователи должны иметь возможность общаться в чате
- Завершенная игра должна быть доступна в записи
- Пользователи должны иметь возможность получать очки по итогам игры, на основе которых строиться рейтинг за неделю, месяц и за все время
- Пользователь должен иметь возможность сыграть игру без регистрации и авторизации на сайте
- Пользователь должен иметь возможность стать премиум подписчиком
- Пользователь должен иметь возможность просматривать свой рейтинг и других пользователей за неделю, месяц и за все время
- Пользователь должен иметь возможность заходить в свой профиль
- Пользователь должен иметь возможность редактировать свой профиль
- При вводе невалидных данных в форму регистрации, система должна выдать ошибку и подсказу для пользователю
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
- Сайт должен отображать количество пользователей онлайн
implicit:
- Пользователь должен иметь возможность зарегистрироваться по номеру телефона
- Пользователь должен иметь возможность авторизоваться по номеру телефона
- Для авторизованных пользователей должен быть раздел обучения сервису
- Сайт должен работать на 2 языках (Русский, English)
- Пользователь должен иметь возможность добавлять друзей на сайте
- Пользователь должен иметь возможность оставить информацию о себе в профиле
- Пользователь должен иметь возможность загрузить аватарку в профиле
- При регистрации пользователя система должна отправлять код подтверждения на Email который указывает пользователь, в целях безопасности
